apiVersion: v1
kind: ConfigMap
metadata:
  name: updatescript
  namespace: myweb
  labels:
    app: myweb
data:
  update.sh: |
    #!/bin/bash

    while true; do
      echo `hostname` > /usr/share/nginx/html/index.html
      X=$((`cat /usr/share/nginx/html/counter.txt` + 1))
      echo $X > /usr/share/nginx/html/counter.txt
      cat /usr/share/nginx/html/counter.txt >> /usr/share/nginx/html/index.html
      sleep 1
    done
