apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hello-world
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
      component: web
  template:
    metadata:
      labels:
        app: hello-world
        component: web
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        name: webserver
        resources:
          limits:
            cpu: "50m"
            memory: "100M"
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 10
        env:
        - name: MY_ENV
          value: myvalue
        ports:
        - containerPort: 8080
          name: http
